louisgrasset/touitomamout

src/helpers/tweet/get-eligible-tweet.ts, src/services/tweets-getter.service.ts
When a tweet has already been synced, we can directly stop the data fetching for the current tweet and skip.
=> feat(tweet-getter): prevent requests when tweet is already synced

src/services/bluesky-sender.service.ts, src/services/mastodon-sender.service.ts
This MR wires the twitter scrapper alternative text property to the corresponding ones on mastodon & bluesky.
Only **images** are supported.
=> feat: add image alt text

src/constants.ts, src/services/tweets-getter.service.ts
It's been a few weeks the sync can take a few **minutes** because of the twitter api rate limit.
Instead of making the sync lasts for a too long time, this MR implements rate limit detection.
A tweet has 60 seconds to get fetched. Timeout is reset at each new successful fetch. After a failure, the sync stops getting new tweets & continues to the next steps
=> feat: add rate limit detection

.github/workflows/cd.yml
This PR allows the CD to deploy the GitHub repository description to docker hub.
=> ci: rely on cd to replicate repo description on docker hub

src/services/bluesky-sender.service.ts, src/services/mastodon-sender.service.ts
Fixes:
* skip post sync when no compatible-media nor text is available
* prevent logging to be blocked when the media is not compatible with bluesky
Closes #29
=> fix(media): skip post sync without text nor media

.github/workflows/ci.yml, .github/workflows/docs.yml
To make CI run a bit quicker, we'll now only run the documentation center jobs only when the `/docs` path has changes.
Since all the docusaurus project is contained inside its own folder, it should not be an issue when docs deps are changed.
=> ci: extract docs related jobs; make them run on docs path change only

src/helpers/cache/migrations/helpers/prevent-migration-on-wrong-version.ts, src/helpers/tweet/__tests__/tweet-formatter.spec.ts, src/helpers/tweet/index.ts, src/helpers/tweet/tweet-formatter.ts, src/services/tweets-getter.service.ts
This PR adds a checks on the 5 most recent tweets.
The posts sync will be skipped if the first eligible tweet (in these 5 most recent one) is already cached. (If not, the sync is done).
=> feat: prevent unecessary sync

src/services/mastodon-sender.service.ts
This PR prevents the `description` field creation when the alt text is actually empty or falsy.
=> fix(mastodon): only inject description field when alt text exists

src/configuration/configuration.ts, src/constants.ts, src/helpers/medias/upload-bluesky-media.ts, src/services/bluesky-sender.service.ts, src/services/posts-synchronizer.service.ts
```bash
content-sync    ⚠ medias: ↯ (1/1) skipped for ☁️ bluesky : Media type not supported (video/mp4)
```
Useful to test the sync process without posting.
```bash
✌️ dry run      ℹ mode enabled (no post will be posted)
```
=> fix(bluesky): properly catch unsupported media error

src/constants.ts, src/helpers/bluesky/build-reply-entry.ts, src/helpers/bluesky/index.ts, src/helpers/cache/migrations/__tests__/cache-migration-0.1.spec.ts, src/helpers/cache/migrations/cache-migration-0.1.ts, src/helpers/cache/migrations/index.ts, src/helpers/cache/run-migrations.ts, src/helpers/logs/ora-progress.ts, src/helpers/post/get-cached-post-chunk.ts, src/helpers/post/get-cached-post-last-chunk.ts, src/helpers/post/make-bluesky-post.ts, src/helpers/post/make-mastodon-post.ts, src/helpers/post/make-post.ts, src/helpers/tweet/__tests__/get-cached-post-chunk.spec.ts, src/helpers/tweet/__tests__/is-tweet-cached.spec.ts, src/helpers/tweet/__tests__/split-tweet-text.spec.ts, src/helpers/tweet/split-tweet-text.ts, src/helpers/tweet/split-tweet-text/get-mastodon-quote-link-section.ts, src/helpers/tweet/split-tweet-text/index.ts, src/services/bluesky-sender.service.ts, src/services/mastodon-sender.service.ts, src/types/cache.ts, src/types/post.ts
This PR adds the following changes:
* a new splitTweetText method
* the related tests
* the implementation for mastodon & bluesky
Closes #28.
=> feat(sync): convert long tweets to threads

src/helpers/cache/__tests__/create-cache.spec.ts, src/helpers/cache/create-cache.ts
This PR fixes the cache creation method.
Previously, Touitomamout was checking for the instance id. Since a recent migration, the instance id was not saved in the same location, so I updated that check, but this is preventing old caches to be compatible with Touitomamout.
This is now fixed.
Thanks to @kai17 for reporting this issue ( #115 ) 🤝 .
=> fix(cache): prevent cache creation to break old data

src/helpers/bluesky/__tests__/fetch-link-metadata.spec.ts, src/helpers/bluesky/__tests__/get-bluesky-link-metadata.spec.ts, src/helpers/bluesky/__tests__/mocks/metadata.ts, src/helpers/bluesky/fetch-link-metadata.ts, src/helpers/bluesky/get-bluesky-chunk-link-metadata.ts, src/helpers/bluesky/get-bluesky-link-metadata.ts, src/helpers/bluesky/index.ts, src/services/bluesky-sender.service.ts, src/types/link-metadata.ts
This PR adds support for link card on bluesky.
If multiple links are present in a givent chunk, only the first one is managed.
Closes #122.
=> feat: support bluesky post embed images for links

package-lock.json, package.json, src/helpers/tweet/__tests__/format-tweet-text.spec.ts, src/helpers/tweet/format-tweet-text.ts
This PR makes the tweet formater to decode the HTML entities so they are properly rendered when the post is sent.
Closes #124 .
=> fix(formatter): decode tweet text HTML entities

docs/src/components/environment-generator/generator.js
The env generator was not generating the `SYNC_MASTODON` not `SYNC_BLUESKY` env variables, leading to confusing situations.
Thanks to @beatstick for catching this bug!
=> fix(generator): add missing SYNC_* env variables output

src/helpers/bluesky/__tests__/get-bluesky-link-metadata.spec.ts, src/helpers/bluesky/get-bluesky-link-metadata.ts, src/services/bluesky-sender.service.ts, src/types/link-metadata.ts
This MR allows Touitomamout not failing while trying to pull the image supposed to be used for the Bluesky card when the image is not referenced.
Closes #156.
=> fix(bluesky): make card image optional

Dockerfile
Removed the (apparently) unnecessary arch specification in the Dockerfile
=> Fix: Get Arm build top work correctly with Sharp

src/services/bluesky-sender.service.ts, src/services/mastodon-sender.service.ts
Sometimes, bluesky sync can break, but errors are not caught. This PR fixes this.
This PR also adds some logging when the `DEBUG` env variable is set.
=> fix(bluesky): add missing catch; add some debug logs

src/configuration/configuration.ts, src/helpers/bluesky/__tests__/get-bluesky-chunk-link-metadata.spec.ts, src/helpers/bluesky/__tests__/get-bluesky-link-metadata.spec.ts, src/helpers/bluesky/get-bluesky-chunk-link-metadata.ts, src/helpers/bluesky/get-bluesky-link-metadata.ts, src/helpers/medias/__tests__/upload-bluesky-media.spec.ts, src/helpers/medias/upload-bluesky-media.ts, src/helpers/post/__tests__/make-bluesky-post.spec.ts, src/helpers/post/__tests__/make-post.spec.ts, src/helpers/post/make-bluesky-post.ts, src/helpers/post/make-post.ts, src/services/__tests__/bluesky-sender.service.spec.ts, src/services/__tests__/posts-synchronizer-service.spec.ts, src/services/__tests__/profile-synchronizer.service.spec.ts, src/services/bluesky-sender.service.ts, src/services/posts-synchronizer.service.ts, src/services/profile-synchronizer.service.ts, src/types/synchronizer-response.ts
This MR removes the usage of BskyAgent, now deprecated, in favor of the new symbol: AtpAgent.
=> chore: migrate from bskyagent to atpagent

src/services/bluesky-sender.service.ts
Chained replies (threads) keep track of the root post to properly display the thread. When adding a new reply to a post, it's therefore necessary to check first if that post was itself a reply: if it is, we simply copy its root post reference
=> fix(bluesky): properly set root post on replies

src/helpers/bluesky/__tests__/create-media-record.spec.ts, src/helpers/bluesky/__tests__/create-media-record.test.ts, src/helpers/bluesky/create-media-record.ts, src/helpers/medias/parse-blob-for-bluesky.ts, src/services/__tests__/bluesky-sender.service.spec.ts, src/services/bluesky-sender.service.ts
Closes https://github.com/louisgrasset/touitomamout/issues/221
=> feat(bluesky): add support for video
